- vtm-ios/build.gradle
- vtm-ios/robovm.xml
We can link to new native folder at the robovm.xml. Don't copy(unzip) to build folder
> Link to new native folder. Don't copy to build folder

- vtm/src/org/oscim/layers/MapEventLayer.java
- vtm/src/org/oscim/map/Map.java
There is a need to distinguish between map position change and interactive map movement performed by user.
> Add event for moving map by user

- vtm/src/org/oscim/layers/tile/TileLayer.java
When reading map from file parallel file access does not make any benefit.
> Set number of loaders

- vtm/src/org/oscim/tiling/source/oscimap4/TileDecoder.java
Let oscimap tiles be decoded from outside the library
> Make tile decoder public

- vtm/src/org/oscim/layers/marker/MarkerRenderer.java
- vtm/src/org/oscim/layers/marker/MarkerSymbol.java
MarkerSymbol currently supports Bitmap only, but TextureRegion might be a better choice if the marker image size is not the power of 2.
> Support TextureRegion to be used for MarkerSymbol

- vtm/src/org/oscim/map/Animator.java
While debugging gestures I've noticed that sometimes zoom animation did not start when the gesture was processed. Further investigation showed that if processing is very fast `millisLeft` is equal to `mDuration` leading to zero advance and infinite animation loop.
Also I have found out that trying to zoom beyond limitations also caused infinite animation loop.
> Fix zoom animation not executed sometimes

- vtm-themes/resources/assets/vtm/mapzen.xml
This PR allows to render capitals earlier using the Mapbox tile format.
A captial is provided like this:
```
{
type: "Point",
properties: {
kind: "locality",
name: "Mumbai",
region_capital: true,
source: "naturalearthdata.com",
min_zoom: 2,
id: 7281,
population: 18978000
},
coordinates: [
975,
3550
]
},
```
or like this:
```
{
type: "Point",
properties: {
kind: "locality",
name: "Algiers",
source: "naturalearthdata.com",
min_zoom: 4,
country_capital: true,
id: 7219,
population: 3354000
},
coordinates: [
555,
3189
]
},
```
I completely removed the min_zoom for locality. I don't know if there might be other side effects, I could not see any.
WDYT?
> Mapbox (Mapzen): Render capital cities early

- vtm-themes/resources/assets/vtm/mapzen.xml
This PR draws neighbourhoods for mapzen tiles. These were not included in the current file. Neighbourhoods seem to be similar to suburbs. I cannot really see why they are different.
> Show Neighbourhoods

- vtm/src/org/oscim/layers/tile/vector/labeling/LabelLayer.java
Let app developer supply custom label loader hook for label layer to be able to implement specific label processing.
> Enable custom label loader in label layer

- vtm/src/org/oscim/layers/MapEventLayer2.java
If map movement is disabled (locked) fling gesture should not ocure.
> Do not fling if map move is disabled

- vtm/src/org/oscim/layers/marker/utils/ScreenUtils.java
Fixed also comments, swaped fill <-> outline
with default radius
with fixed radius
> Cluster marker is clipped, fixed by reducing radius

- vtm/src/org/oscim/layers/PathLayer.java
If distance is too short calculation becomes broken and point(0,0) is added to the path.
> Do not try to calculate zero length great circle path

- docs/Changelog.md
- vtm-android-example/src/org/oscim/android/test/PathOverlayActivity.java
- vtm-jts/src/org/oscim/layers/vector/PathLayer.java
- vtm-jts/src/org/oscim/layers/vector/VectorLayer.java
- vtm-playground/src/org/oscim/test/PathLayerTest.java
- vtm/src/org/oscim/layers/PathLayer.java
- vtm/src/org/oscim/utils/GeoPointUtils.java
Fixes #316, fixes #424.
Implement touch events for `PathLayer`, `VectorLayer` (polygon) overlays.
> PathLayer, VectorLayer (polygon) overlays touch events

- vtm/src/org/oscim/map/ViewController.java
- vtm/src/org/oscim/map/Viewport.java
recycled variables were accessed non synchronized (and therefore non
thread safe) causing errors once multiple threads were used interacting
with the Viewport
> fixed thread safety problem in Viewport

- vtm-ios/src/org/oscim/ios/backend/IosCanvas.java
- vtm-ios/src/org/oscim/ios/backend/IosPaint.java
After the changes from #236 to the scaling, I didn't really like the text drawing under iOS anymore, so I reworked it again!
Especially the handling of the text stroke was not correct!
before PR:
after change with PR:
> Fix text drawing with stroke on iOS

- vtm-extras/src/org/oscim/tiling/source/geojson/GeoJsonTileDecoder.java
- vtm-extras/src/org/oscim/tiling/source/oscimap2/OSciMap2TileSource.java
- vtm-json/src/org/oscim/tiling/source/geojson/TileDecoder.java
- vtm-web/src/org/oscim/tiling/source/geojson/GeoJsonTileDecoder.java
- vtm/src/org/oscim/core/TagSet.java
- vtm/src/org/oscim/layers/tile/vector/OsmTileLayer.java
- vtm/src/org/oscim/theme/MatchingCacheKey.java
- vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java
- vtm/src/org/oscim/tiling/source/mapfile/OSMUtils.java
- vtm/src/org/oscim/tiling/source/oscimap4/TileDecoder.java
`TagSet` is sometimes unsafe and not always clear at which position the `numTags` counter is pointing. This should be more convenient.
> TagSet: numTags and tag array as private

- vtm-android/src/org/oscim/android/theme/AssetsRenderTheme.java
- vtm-themes/src/org/oscim/theme/VtmThemes.java
- vtm/src/org/oscim/theme/ExternalRenderTheme.java
- vtm/src/org/oscim/theme/StreamRenderTheme.java
- vtm/src/org/oscim/theme/ThemeFile.java
- vtm/src/org/oscim/theme/ThemeLoader.java
This is not a good solution to always read theme twice to check if it is in native or mapsforge format. Despite `ThemeUtils` closes `InputStream` asap it is not always a good solution. In my case I construct theme from many pieces depending on user input and I have to do it twice just to flag that the theme is in native format.
As `ThemeFile` is an interface more clear solution is to let its implementation decide what format it implements. General implementations use `ThemeUtils` as before.
> Do not read theme twice if format is predefined

- vtm/src/org/oscim/layers/tile/buildings/BuildingLayer.java
- vtm/src/org/oscim/layers/tile/buildings/S3DBTileLoader.java
- vtm/src/org/oscim/renderer/ExtrusionRenderer.java
- vtm/src/org/oscim/renderer/bucket/ExtrusionBucket.java
Refactor some attributes in `ExtrusionBucket`
- color and colors as private (add getters)
- renamed `add` (for meshes) to `addMesh`
- renamed `add` (for polygons) to `addPoly`
Notes: `add`(mesh) and `add`(poly) not give the same result with other parameters, so this should be more separated.
> Refactor ExtrusionBucket

- vtm-json/src/org/oscim/tiling/source/geojson/OpenMapTilesGeojsonTileSource.java
Fixed Maxzoom for OpenMapTiles.
See: https://free.tilehosting.com/data/v3.json?key=[YOUR_KEY]
Prints: `maxzoom: 14`
> OpenMapTiles Max-Zoom Fix

- vtm/src/org/oscim/layers/PathLayer.java
It was misleading as there exist `RenderBucket` and `RenderTheme`, too, but here it's a `Renderer`.
> PathLayer: refactor 'RenderPath' to 'PathRenderer'

- vtm/src/org/oscim/layers/tile/buildings/S3DBLayer.java
Dependent on latitude roofs with tag "roof:angle" now have a better height estimation.
> S3DBLayer: fix roof height estimation based on tag "roof:angle"

- vtm-playground/src/org/oscim/test/gdx/poi3d/GdxModelRenderer.java
- vtm-playground/src/org/oscim/test/gdx/poi3d/GdxRenderer3D.java
- vtm-playground/src/org/oscim/test/gdx/poi3d/GdxRenderer3D2.java
- vtm-playground/src/org/oscim/test/renderer/CustomRenderer.java
- vtm/src/org/oscim/renderer/GLState.java
Unbind/bind via GLState to ensure no buffer is replaced by accident without the knowledge of other renderers (fix #601).
> Playground renderer: bind with GLState (#601)

- vtm/src/org/oscim/utils/geom/TileClipper.java
`TileClipper` hasn't worked flawless with asynchronous calls, and e.g. `mGeoOut` can not be used safely then.
> TileClipper: synchronize clip

- vtm/src/org/oscim/utils/ColorUtil.java
- vtm/src/org/oscim/utils/geom/GeometryUtils.java
Some utils needed for sun calculations (#575).
> Utils for sun calculations

- vtm/src/org/oscim/renderer/light/Sun.java
In default color map the colors are initiated both with 0 which is the optimal value when progress is at 0. So it has a fraction of 0 / 0 = NaN.
> Sun: fix color update on init equal progress

- vtm/src/org/oscim/layers/tile/buildings/BuildingLayer.java
If `BuildingLayer` is created before `RenderTheme` is set, the theme isn't available for `BuildingLayer`. Or the theme is set afterwards...
Example: OverpassTest, MultiMapViewActivity, SimpleMapActivity, SimpleMapTest.
This had no impact, cause they all don't use `tag-transform` like NextzenMvtActivity. But if so that should be fixed.
> Fix Rendertheme set after creation of BuildingLayer

- vtm-themes/resources/assets/vtm/default.xml
- vtm/src/org/oscim/layers/tile/buildings/S3DBLayer.java
- vtm/src/org/oscim/layers/tile/buildings/S3DBTileLoader.java
- vtm/src/org/oscim/layers/tile/buildings/S3DBUtils.java
Can test again in `ExtrusionTest`. To see real colors you have to modify `S3DBUtils`:
```
private static final double HSV_S = 1.0;
private static final double HSV_V = 1.0;
```
We can consider to use this tag transform in other themes, too. But there's always the fall back to css colors already and they are desatured anyway.
> S3DB: modify colors in theme

- resources/rendertheme.xsd
- vtm-android/src/org/oscim/android/canvas/AndroidCanvas.java
- vtm-themes/resources/assets/vtm/default.xml
- vtm-themes/resources/assets/vtm/mapzen.xml
- vtm-themes/resources/assets/vtm/newtron.xml
- vtm-themes/resources/assets/vtm/openmaptiles.xml
- vtm-themes/resources/assets/vtm/osmagray.xml
- vtm-themes/resources/assets/vtm/osmarender.xml
- vtm-themes/resources/assets/vtm/tronrender.xml
- vtm/src/org/oscim/renderer/bucket/TextBucket.java
- vtm/src/org/oscim/theme/XmlThemeBuilder.java
- vtm/src/org/oscim/theme/styles/TextStyle.java
Add in theme text rules a background color option, useful for cases like highway shields.
```xml
<style-text caption="true" style="bold" fill="#ffffff" id="ref" k="ref" priority="2" size="12" bg-fill="#45a976" />
```
> Render themes: text background color (highway shields)

- docs/Changelog.md
- vtm-android/src/org/oscim/android/MapView.java
- vtm-android/src/org/oscim/android/gl/GlContextFactory.java
Use OpenGL ES 2.0 as default on Android for performance & stability reasons.
There are reports for performance & rendering issues on many devices using OpenGL ES 3.0.
OpenGL ES 3.0 is not a prerequisite for core library functions, can be set as option via the flag:
```java
MapView.OPENGL_VERSION
```
See also: https://godotengine.org/article/abandoning-gles3-vulkan-and-gles2
> Android: OpenGL ES 2.0 default for performance / stability

- docs/Changelog.md
- vtm-android-example/res/raw/marker.svg
- vtm-android-example/src/org/oscim/android/test/LocationActivity.java
- vtm-android-example/src/org/oscim/android/test/LocationTextureActivity.java
- vtm-app/src/org/oscim/app/location/Compass.java
- vtm/resources/assets/shaders/accuracy_1.glsl
- vtm/src/org/oscim/layers/LocationLayer.java
- vtm/src/org/oscim/layers/LocationTextureLayer.java
- vtm/src/org/oscim/renderer/LocationCallback.java
- vtm/src/org/oscim/renderer/LocationRenderer.java
- vtm/src/org/oscim/renderer/LocationTextureRenderer.java
Rewrite `LocationTextureRenderer` and optimize it similarly to `LocationRenderer`.
> Location texture renderer: rewrite and optimize

- vtm-android-example/src/org/oscim/android/test/ClusterMarkerOverlayActivity.java
- vtm-android-example/src/org/oscim/android/test/MarkerOverlayActivity.java
- vtm-android-example/src/org/oscim/android/test/PoiSearchActivity.java
- vtm-android/src/org/oscim/android/canvas/AndroidGraphics.java
Seems a problem at drawables to bitmaps conversion on newer Android (`BitmapDrawable.getBitmap`).
We could use a simpler bitmap read and avoid all that code workarounds.
See https://github.com/mapsforge/mapsforge/issues/1138
> AndroidGraphics: drawable to bitmap for Android >= 9

- docs/Changelog.md
- vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java
- vtm/src/org/oscim/utils/Parameters.java
Heavy maps like Germany or Netherlands can have performance issues in 2nd zoom interval (8-11).
Can offer an option to reduce points on-the-fly while reading from map files, without serious data loss.
> Mapsforge: reduce points on-the-fly while reading from map files

- docs/Changelog.md
- vtm/src/org/oscim/renderer/bucket/LineBucket.java
Should now work globally for render themes and path layers.
See #107
> Fix stroke cap line ending

- vtm-android-example/src/org/oscim/android/test/GettingStarted.java
- vtm-android-example/src/org/oscim/android/test/MapsforgeActivity.java
- vtm-android-example/src/org/oscim/android/test/SimpleMapActivity.java
- vtm/src/org/oscim/scalebar/MapScaleBarLayer.java
add onDetach-method to MapScaleBarLayer to free resources automatically
removed mapScaleBar.destroy() methods from onDestroy-Activity methods
changed global mapScaleBar-variables to local
> MapScaleBarLayer: add onDetach-method to free resources automatically

- vtm-android-example/src/org/oscim/android/test/MapsforgeActivity.java
- vtm-android-example/src/org/oscim/android/test/PoiSearchActivity.java
- vtm-android-example/src/org/oscim/android/test/ReverseGeocodeActivity.java
small improvements to android-examples, reducing necessary global variables and demonstrating the  VectorTileLayer.getTileSource()-method
> android-examples: demonstrate usage of VectorTileLayer.getTileSource()

- vtm/src/org/oscim/event/EventDispatcher.java
Hi!
I'm reusing a single `MapView` in my app, but to clear it completely it's necessary to remove the `EventListener`s as well. Using `EventDispatcher::unbind` is not very convenient, because it requires  keeping the old listeners around.
> Add EventDispatcher::clear

- build.gradle
See https://github.com/mapsforge/mapsforge/pull/1182.
> Use --release=7 for compiling the non-android libraries on Java >= 9

- vtm-android-example/build.gradle
- vtm-android-gdx/build.gradle
- vtm-android-mvt/build.gradle
- vtm-android/build.gradle
Throw a gradle exception during build, if the required environment variable "ANDROID_HOME" is undefined
(only applies to Android-related builds)
> Throw exception on missing envvar for Android-related builds

- vtm-web-app/build.gradle
- vtm-web/build.gradle
Deprecated properties in Gradle 8 are making `vtm-web-app` build fail. Upgraded gwt-gradle-plugin and gretty.
> Updated external library versions in vtm-web to support gradle 8

- vtm-android-example/src/org/oscim/android/test/VectorLayerActivity.java
- vtm-jts/src/org/oscim/layers/vector/VectorLayer.java
- vtm-jts/src/org/oscim/layers/vector/geometries/Style.java
This PR adds a new parameter dropDistance to the VTM Style object. In addition to the already existing boolean parameter pointReduction (which, if set, applies a default fixed dropDistance to lines/points/polygons), it allows to specify a dropDistance directly.
This parameter can be used to mitigate the zooming problems specified in #1082.
The PR also adds an example polyline to the android-example `VectorLayerActivity` in the area of Hamburg, Germany. demonstrating the usage of this parameter.
Zooming in:
> VTM Style: allow adding dropDistance directly (related to #1082)

- vtm/src/org/oscim/map/Layers.java
Fix https://github.com/mapsforge/vtm/issues/1116
> Layers: bind added layer in set

- vtm-themes/resources/assets/vtm/motorider.xml
- https://github.com/devemux86/cruiser/discussions/176
Example using OpenAndro "Lake District" map showing contour lines, mountain passes+peaks:
(some peaks have names, others just have a height value)
Example using Mapsforge "United Kingdom" map showing roads and various POIs (enabled via Layers menu):
> Motorider map theme improvements, #1183
