vtm/src/org/oscim/renderer/BitmapRenderer.java, vtm/src/org/oscim/renderer/GLViewport.java
Adds ability to offset bitmap overlay (no need to use transparent margins).
P.S. I do not understand the meaning of `scale` so I have copied it as-is.
=> Set screen offset for bitmap rendering

vtm-android-example/AndroidManifest.xml, vtm-android-example/res/layout/activity_map_multi.xml, vtm-android-example/src/org/oscim/android/test/MultiMapActivity.java, vtm-android-example/src/org/oscim/android/test/Samples.java
=> Multi Map Sample

vtm-android-example/src/org/oscim/android/test/BitmapTileMapActivity.java, vtm-android-example/src/org/oscim/android/test/SimpleMapActivity.java, vtm-gdx/src/org/oscim/gdx/InputHandler.java, vtm-tests/test/org/oscim/layers/MapEventLayerTest.java, vtm/src/org/oscim/layers/MapEventLayer.java, vtm/src/org/oscim/map/Animator.java, vtm/src/org/oscim/utils/Easing.java
Some kind of accessory, which adds an option to animator not to move only linear but with other easing functions.
=> Added easing functions which currently works with Animator

vtm/src/org/oscim/tiling/source/mapfile/OSMUtils.java
Amenity can be point or area (https://wiki.openstreetmap.org/wiki/Key:amenity), so treat is as closed way (area).
=> Treat amenity as area

vtm/src/org/oscim/utils/TextureAtlasUtils.java
Create a Map<Object, TextureRegion> from Map<Object, Bitmap>
will help for issue :   Render themes: SVG texture atlas #63
=> Create TextureAtlas with Textureregions from Bitmap list

vtm-gdx/src/org/oscim/gdx/InputHandler.java, vtm/src/org/oscim/layers/Layer.java, vtm/src/org/oscim/map/Layers.java
This PR treats the layer.enabled flag.
As an example, you can turn the BuildingLayer on or off in the Playground Project by pressing the 'B' key!
=> Layer.setEnabled (false) has been ignored.

docs/Changelog.md, vtm-tests/test/org/oscim/core/MercatorProjectionTest.java, vtm/src/org/oscim/core/BoundingBox.java, vtm/src/org/oscim/core/MercatorProjection.java, vtm/src/org/oscim/core/Tile.java, vtm/src/org/oscim/layers/LocationLayer.java, vtm/src/org/oscim/layers/tile/buildings/BuildingLayer.java, vtm/src/org/oscim/layers/tile/buildings/S3DBTileLoader.java, vtm/src/org/oscim/utils/GeoPointUtils.java
Fixes #396.
We have implemented in Mapsforge many core utilities which are useful in several cases and can have them also in VTM.
=> Core utilities #396

docs/Changelog.md, vtm-android-example/AndroidManifest.xml, vtm-android-example/res/values/strings.xml, vtm-android-example/src/org/oscim/android/test/MapsforgeMapActivity.java, vtm-android-example/src/org/oscim/android/test/PoiSearchActivity.java, vtm-android-example/src/org/oscim/android/test/ReverseGeocodeActivity.java, vtm-android-example/src/org/oscim/android/test/Samples.java, vtm/src/org/oscim/layers/tile/MapTile.java, vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java, vtm/src/org/oscim/tiling/source/mapfile/MapReadResult.java, vtm/src/org/oscim/tiling/source/mapfile/MultiMapDatabase.java, vtm/src/org/oscim/tiling/source/mapfile/MultiMapFileTileSource.java, vtm/src/org/oscim/tiling/source/mapfile/PoiWayBundle.java, vtm/src/org/oscim/tiling/source/mapfile/PointOfInterest.java, vtm/src/org/oscim/tiling/source/mapfile/QueryCalculations.java, vtm/src/org/oscim/tiling/source/mapfile/Way.java
=> Mapsforge Reverse Geocoding #383

docs/Applications.md
This is our app using vtm library. It's old, though...
=> Added my app to Applications.md

vtm/src/org/oscim/core/Tag.java
Small PR to complete needed S3DB tags
=> Add needed osm-tags (S3DB)

vtm-themes/resources/assets/vtm/default.xml, vtm-themes/resources/assets/vtm/newtron.xml, vtm-themes/resources/assets/vtm/openmaptiles.xml, vtm-themes/resources/assets/vtm/tronrender.xml, vtm-web-app/resources/assets/vtm/default_atlas.xml
=> Fix Internal render theme styles order (#490)

docs/Changelog.md, resources/rendertheme.xsd, vtm-json/src/org/oscim/tiling/source/geojson/GeojsonTileSource.java, vtm-json/src/org/oscim/tiling/source/geojson/MapzenGeojsonTileSource.java, vtm-json/src/org/oscim/tiling/source/geojson/NextzenGeojsonTileSource.java, vtm-mvt/src/org/oscim/tiling/source/mvt/MapzenMvtTileSource.java, vtm-mvt/src/org/oscim/tiling/source/mvt/NextzenMvtTileSource.java, vtm-mvt/src/org/oscim/tiling/source/mvt/OpenMapTilesMvtTileSource.java, vtm-themes/resources/assets/vtm/openmaptiles.xml, vtm-web/src/org/oscim/gdx/emu/org/oscim/tiling/source/bitmap/BitmapTileSource.java, vtm/src/org/oscim/layers/tile/TileManager.java, vtm/src/org/oscim/layers/tile/vector/OsmTileLayer.java, vtm/src/org/oscim/layers/tile/vector/VectorTileLoader.java, vtm/src/org/oscim/map/Viewport.java, vtm/src/org/oscim/tiling/OverzoomDataSink.java, vtm/src/org/oscim/tiling/OverzoomTileDataSource.java, vtm/src/org/oscim/tiling/TileDataSink.java, vtm/src/org/oscim/tiling/TileSource.java, vtm/src/org/oscim/tiling/source/UrlTileSource.java, vtm/src/org/oscim/tiling/source/bitmap/BitmapTileSource.java, vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java, vtm/src/org/oscim/tiling/source/mapfile/MapFileTileSource.java, vtm/src/org/oscim/tiling/source/mapfile/MultiMapDatabase.java, vtm/src/org/oscim/tiling/source/mapfile/MultiMapFileTileSource.java, vtm/src/org/oscim/tiling/source/oscimap4/OSciMap4TileSource.java
Fix #393 
Map overzoom implementation, i.e. separation of data extraction and rendering.
=> Map overzoom implementation

vtm/src/org/oscim/layers/tile/buildings/S3DBUtils.java
If there is a shape with tagged as `skillion`, the calculation is now based on the two best points at the more appropriate side (as standing triangles have no top side). (E.g. [St. Lorenz](https://www.openstreetmap.org/way/298017979) at Nuremberg).
Before always the top side was used.
=> S3DB: Fix skillion calculation on (triangular) shapes

vtm/resources/assets/shaders/linetex_layer_tex.glsl, vtm/src/org/oscim/renderer/bucket/LineTexBucket.java
- Revert TexLineBucket: lineLength initialization
- Revert lineTex_layer_tex shader: +1
=> Issue 532: Revert some code

docs/Rendertheme.md
I adopted the basic structure from Mapsforge Render-Themes. And I tried to explain some difficult attributes.
@devemux86: You can have a look, if it's all correct? Especially the style menus may work different.
=> Render-theme docs

vtm-playground/src/org/oscim/test/GdxSpriteBatchTest.java, vtm-playground/src/org/oscim/test/gdx/poi3d/GdxModelRenderer.java, vtm-playground/src/org/oscim/test/gdx/poi3d/GdxRenderer3D.java, vtm-playground/src/org/oscim/test/gdx/poi3d/GdxRenderer3D2.java, vtm-playground/src/org/oscim/test/renderer/CustomRenderer.java, vtm-playground/src/org/oscim/test/renderer/HexagonRenderTest.java, vtm/src/org/oscim/renderer/ExtrusionRenderer.java, vtm/src/org/oscim/renderer/GLState.java, vtm/src/org/oscim/renderer/LocationRenderer.java, vtm/src/org/oscim/renderer/LocationTextureRenderer.java, vtm/src/org/oscim/renderer/MapRenderer.java, vtm/src/org/oscim/renderer/bucket/CircleBucket.java, vtm/src/org/oscim/renderer/bucket/HairLineBucket.java, vtm/src/org/oscim/renderer/bucket/LineBucket.java, vtm/src/org/oscim/renderer/bucket/LineTexBucket.java, vtm/src/org/oscim/renderer/bucket/MeshBucket.java, vtm/src/org/oscim/renderer/bucket/PolygonBucket.java
=> GLState: State DISABLED = -1

vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java
=> MapDatabase: separate POIs

vtm-playground/src/org/oscim/test/gdx/poi3d/ModelHolder.java, vtm-playground/src/org/oscim/test/gdx/poi3d/Poi3DLayer.java
- insert MIN_ZOOM
- support multiple models / multiple tags
- parameter RANDOM_TRANSFORM
- use ground scale
Sometimes I get this error:
```
Exception in thread "LWJGL Application" org.lwjgl.opengl.OpenGLException: Cannot use offsets when Element Array Buffer Object is disabled
at org.lwjgl.opengl.GLChecks.ensureElementVBOenabled(GLChecks.java:89)
at org.lwjgl.opengl.GL11.glDrawElements(GL11.java:1117)
at org.oscim.gdx.LwjglGL20.drawElements(LwjglGL20.java:842)
at org.oscim.renderer.bucket.TextureBucket.render(TextureBucket.java:173)
at org.oscim.renderer.bucket.TextureBucket$Renderer.draw(TextureBucket.java:154)
at org.oscim.layers.tile.vector.labeling.TextRenderer.render(TextRenderer.java:87)
at org.oscim.renderer.MapRenderer.draw(MapRenderer.java:155)
at …
```
=> Improve Poi3DLayer

vtm-models/resources/assets/models/natural/tree.g3dj
=> vtm-models: make `tree.g3dj` metric

vtm-gdx-poi3d/src/org/oscim/gdx/poi3d/Poi3DLayer.java
- add ZoomLimiter
- improved line / area model placement,
- optional hiding theme renders
See #610.
=> Poi3DLayer improvements v2

vtm-app/src/org/osmdroid/location/GeocoderNominatim.java, vtm-theme-comparator/src/org/oscim/theme/comparator/editor/ThemeLoader.java, vtm-theme-comparator/src/org/oscim/theme/comparator/location/LocationData.java, vtm-web/src/org/oscim/gdx/emu/com/badlogic/gdx/backends/gwt/GwtApplication.java, vtm-web/src/org/oscim/tiling/source/geojson/JsArrayCollection.java, vtm/src/org/oscim/layers/tile/MapTile.java, vtm/src/org/oscim/layers/tile/TileLayer.java, vtm/src/org/oscim/layers/vector/AbstractVectorLayer.java, vtm/src/org/oscim/renderer/GLMatrix.java, vtm/src/org/oscim/theme/styles/RenderStyle.java, vtm/src/org/oscim/utils/animation/Easing.java, vtm/src/org/oscim/utils/math/Interpolation.java, vtm/src/org/oscim/utils/math/MathUtils.java
See: 
https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.3
And:
https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.3.1
=> Reorder method / field modifiers

vtm/resources/assets/shaders/line_aa.glsl, vtm/resources/assets/shaders/line_aa_proj.glsl, vtm/resources/assets/shaders/linetex_layer_tex.glsl, vtm/src/org/oscim/renderer/bucket/LineBucket.java, vtm/src/org/oscim/renderer/bucket/LineTexBucket.java
For consistency with other shaders.
=> Shaders: u_mode uniform as integer

vtm/resources/assets/shaders/line_aa.glsl, vtm/resources/assets/shaders/line_aa_proj.glsl, vtm/resources/assets/shaders/linetex_layer_tex.glsl, vtm/resources/assets/shaders/poly_texture.glsl, vtm/resources/assets/shaders/polygon_layer_tex.glsl, vtm/resources/assets/shaders/texture_alpha.glsl, vtm/resources/assets/shaders/texture_layer.glsl, vtm/src/org/oscim/renderer/bucket/BitmapBucket.java, vtm/src/org/oscim/renderer/bucket/TextureBucket.java
=> Adapt / refactor shader uniforms and attributes

docs/Applications.md
just added my GPSLogger II app to the docs
the app is just releases ad 2.0.0.31 with integrated VTM  (and Mapsforge as fallback - already listed)
thanks for all the effort
=> added GPSLogger II

docs/Changelog.md, resources/rendertheme.xsd, vtm-themes/resources/assets/vtm/default.xml, vtm-themes/resources/assets/vtm/mapzen.xml, vtm-themes/resources/assets/vtm/newtron.xml, vtm-themes/resources/assets/vtm/openmaptiles.xml, vtm-themes/resources/assets/vtm/osmagray.xml, vtm-themes/resources/assets/vtm/osmarender.xml, vtm-themes/resources/assets/vtm/tronrender.xml, vtm/src/org/oscim/layers/tile/vector/labeling/LabelPlacement.java, vtm/src/org/oscim/layers/tile/vector/labeling/WayDecorator.java, vtm/src/org/oscim/theme/XmlThemeBuilder.java, vtm/src/org/oscim/theme/styles/LineStyle.java, vtm/src/org/oscim/theme/styles/SymbolStyle.java
=> Render themes - symbols on lines: add billboard, rotate options

vtm/src/org/oscim/layers/tile/buildings/S3DBUtils.java
See #744 
@andreynovikov now defined as constants.
=> S3DB: shape profiles as constants

vtm/src/org/oscim/map/ViewController.java, vtm/src/org/oscim/renderer/LocationRenderer.java, vtm/src/org/oscim/renderer/LocationTextureRenderer.java
See discussion in [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/cURFfuf6Dag).
Note: should disable it afterwards, with touch gestures, etc.
=> Location renderers: allow fixed center position

vtm-themes/resources/assets/vtm/default.xml, vtm-themes/resources/assets/vtm/mapzen.xml, vtm-themes/resources/assets/vtm/newtron.xml, vtm-themes/resources/assets/vtm/openmaptiles.xml, vtm-themes/resources/assets/vtm/osmagray.xml, vtm-themes/resources/assets/vtm/osmarender.xml, vtm-themes/resources/assets/vtm/tronrender.xml
=> Render themes: avoid patterns and textures because of old GPU issues

vtm/src/org/oscim/layers/tile/vector/VectorTileLayer.java
add getter for mTileSource in VectorTileLayer
=> VectorTileLayer.getTileSource

docs/Changelog.md, docs/Integration.md, vtm-android-example/src/org/oscim/android/filepicker/ValidRenderTheme.java, vtm-app/src/org/oscim/app/filefilter/ValidRenderTheme.java, vtm-web/src/org/oscim/gdx/emu/org/xmlpull/v1/XmlPullParser.java, vtm-web/src/org/oscim/gdx/emu/org/xmlpull/v1/XmlPullParserException.java, vtm-web/src/org/oscim/gdx/emu/org/xmlpull/v1/XmlPullParserFactory.java, vtm-web/src/org/oscim/gdx/emu/org/xmlpull/v1/XmlSerializer.java, vtm/build.gradle, vtm/src/org/oscim/theme/XmlAtlasThemeBuilder.java, vtm/src/org/oscim/theme/XmlThemeBuilder.java
=> Render theme xml pull parser

vtm-android-example/src/org/oscim/android/test/MapsforgeActivity.java, vtm-tests/test/org/oscim/theme/ZipXmlThemeResourceProviderTest.java, vtm/src/org/oscim/theme/ZipXmlThemeResourceProvider.java
See https://github.com/mapsforge/mapsforge/pull/1190.
=> ZipXmlThemeResourceProvider: add method to just scan zip for xml themes

vtm-android/src/org/oscim/android/theme/ContentResolverResourceProvider.java
See https://github.com/mapsforge/mapsforge/pull/1191.
=> ContentResolverResourceProvider should handle document Uris correctly

vtm-android/src/org/oscim/android/theme/ContentResolverResourceProvider.java
See https://github.com/mapsforge/mapsforge/pull/1200.
=> ContentResolverResourceProvider: honor also absolute file references in theme resources

vtm-http/src/org/oscim/tiling/source/OkHttpEngine.java
=> OkHttpEngine: close catching Exception

docs/Changelog.md, vtm-playground/src/org/oscim/test/MapsforgeTest.java, vtm/src/org/oscim/core/MapElement.java, vtm/src/org/oscim/layers/tile/vector/VectorTileLoader.java, vtm/src/org/oscim/tiling/TileDataSink.java, vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java, vtm/src/org/oscim/tiling/source/mapfile/MapReadResult.java, vtm/src/org/oscim/tiling/source/mapfile/MultiMapDatabase.java, vtm/src/org/oscim/tiling/source/mapfile/MultiMapFileTileSource.java
- germany/baden-wuerttemberg.map
- germany/bayern.map
- austria.map
- switzerland.map
=> Mapsforge: deduplicate maps, fix overlapping map regions

docs/Changelog.md, vtm/src/org/oscim/core/TagSet.java, vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java, vtm/src/org/oscim/utils/Parameters.java
=> Mapsforge: simplification exceptions

vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java
=> Mapsforge: overlapping map region improvements #905

README.md
Set link to the demo page to new URL
=> Revised description in README.md

vtm/src/org/oscim/theme/RenderTheme.java
See: https://github.com/mapsforge/mapsforge/pull/1369
=> RenderTheme: increase cache size

vtm/src/org/oscim/renderer/bucket/LineBucket.java, vtm/src/org/oscim/utils/Parameters.java
Related to https://github.com/mapsforge/vtm/issues/1082.
=> LineBucket: transparent lines

vtm-android-example/src/org/oscim/android/test/MapFragment.java
I was playing around with the fragment example hoping that I somehow could reproduce https://github.com/cgeo/cgeo/issues/15100 (unfortunately without success). On the way, I couldn't resist doing some small refactoring.
- split map and theme load method
- add toasts
- ...
=> minor fragment example changes

vtm-android-example/res/values-v35/styles.xml
- Improves https://github.com/mapsforge/vtm/pull/1141 https://github.com/mapsforge/vtm/pull/1146
=> Android 15 improvements

vtm-themes/resources/assets/vtm/motorider.xml
- https://github.com/devemux86/cruiser/discussions/176
=> Motorider map theme improvements, #1183

vtm-themes/resources/assets/vtm/biker.xml
- https://github.com/devemux86/cruiser/discussions/730
_General map views at various zoom-levels with hillshading enabled:_
_Another example of hillshading including "Mountain peaks":_
=> Biker map theme improvements, #1192

vtm-themes/resources/assets/vtm/biker.xml, vtm-themes/resources/assets/vtm/motorider.xml
- https://github.com/devemux86/cruiser/discussions/744
- https://github.com/devemux86/cruiser/discussions/730
=> Motorider and Biker map theme improvements, #1183, #1192

docs/Changelog.md, vtm-android-example/res/menu/theme_menu.xml, vtm-android-example/res/values/strings.xml, vtm-android-example/src/org/oscim/android/test/BaseMapActivity.java, vtm-android-example/src/org/oscim/android/test/MapsforgeActivity.java, vtm-gdx/src/org/oscim/gdx/InputHandler.java, vtm-themes/resources/assets/vtm/dark.xml, vtm-themes/resources/assets/vtm/indigo.xml, vtm-themes/src/org/oscim/theme/internal/VtmThemes.java
- https://github.com/devemux86/cruiser/discussions/739
=> Dark and Indigo map themes, #1229

vtm-themes/resources/assets/vtm/biker.xml, vtm-themes/resources/assets/vtm/dark.xml, vtm-themes/resources/assets/vtm/indigo.xml, vtm-themes/resources/assets/vtm/motorider.xml
- https://github.com/devemux86/cruiser/discussions/744
- https://github.com/devemux86/cruiser/discussions/730
- https://github.com/devemux86/cruiser/discussions/739
=> Map theme improvements, #1183, #1192, #1229

.github/workflows/android.yml, README.md, docs/Integration.md, vtm-android-example/build.gradle
OSSRH service reached end-of-life on 2025-06-30
https://central.sonatype.org/news/20250326_ossrh_sunset/
=> Disable Maven publish because OSSRH service reached end-of-life on 2025-06-30

vtm-themes/resources/assets/vtm/biker.xml, vtm-themes/resources/assets/vtm/dark.xml, vtm-themes/resources/assets/vtm/indigo.xml, vtm-themes/resources/assets/vtm/motorider.xml
- https://github.com/devemux86/cruiser/discussions/822
=> Map theme languages: Danish, Portuguese, Swedish
